### PR TITLE
new: [blog] Zeek JavaScript MISP integration

### PR DESCRIPTION
**Pull request by awelzel**
Hello @adulau - this is a draft about the zeekjs-misp project as discussed with Nico from Corelight.

Would this be a good fit to publish?

### CODE REVIEW

**Comment by adulau** [comment]
This is awesome. Thanks a lot for the contribution.

**Comment by adulau** [comment]
Maybe a small diagram to explain the overall flows between MISP and Zeek ? and we are good to go for the publishing.

**Comment by awelzel** [comment]
cc @nrsnbm

**Comment by awelzel** [comment]
@adulau , I've added a diagram and used it as banner, too. Also fixed the date to be 2024 :-)

**Comment by adulau** [comment]
This is great. I’ll merge it and officially publish the blog post on Monday! Thanks again for your contribution.

**Comment by adulau** [comment]
It's now online -> https://www.misp-project.org/2024/01/03/Zeek_JavaScript_MISP_Integration.html/  feel free to share it. I'll share it on the official social pages from MISP Project. Thanks again for your contribution.

**Pull request merged**
