### PR TITLE
Cleanup Event pages

### PR DESCRIPTION
**Pull request by Kagee**
Split events into Upcoming and Past events. Tough cleanup of design on both pages (see screenshots). Original commit just linked to xing iframe urls, but they looked odd. Implemented collapsible event registration using already present Bootstrap.js. Minor tweak to custom.css to render ul ul tags better.

2022-08-02-200603_784x775_scrot

2022-08-02-200356_750x824_scrot

2022-08-02-213404_596x538_scrot

### CODE REVIEW

**Comment by iglocska** [comment]
That looks lovely!

**Comment by Kagee** [comment]
I still have some ideas after having read up on the Xing documentation, so expect at least one more commit before I ask for å merge.

**Comment by adulau** [comment]
Thanks a lot! I'll wait for the last commit before merging and publishing.

**Comment by Kagee** [comment]
Last commit was to make the linter happy. I have also tested a registration and xing-login using the iframe.

**Pull request merged**
